all:
	cd src/ && make

install:
	cd src/ && make install

clean:
	cd src/ && make clean
	cd tests/ && make clean

test:
	cd src/ && make test

test-all:
	cd tests/ && make test-all

.PHONY: all clean install test test-all
